frase = "Curso em video python"

# print(frase)
# print(frase[3])
# print(frase[3:13])
# print(frase[:13])
# print(frase[1:15])
# print(frase[1:15:2])
# print(frase[::2])

# print("""fasdfasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaernasdfasdgafdgjadfngçldafngçkjdafngçajdfngladnfogainrgóiaenrgóianrǵoinafoḱgnsadfógnórgnóiegnáokfngĺsdkngóweingóngósngóaern""")
# print(frase.count('o'))
# print(frase.upper().count('O'))
# print(len(frase.strip()))
# print(len(frase))
# print(frase.replace("python", "Android"))
# frase = frase.replace("python", "Android")
# print(frase)
# print('Curso' in frase)
# print(frase.find('Curso'))
# print(frase.lower().find('Curso'))
# dividido = frase.split()
# print(dividido[0][0])
